__default__:
    account: sansam-lab
    partition: serial
    time: 08:00:00
    cpus-per-task: 2
    mem: 16G
    output: results/logs/slurm-%x.%A.%a.log
    error: results/errors/slurm-%x.%A.%a.err

# ------------------------------------------------------------------------------
# Quality Control
# ------------------------------------------------------------------------------

fastqc_raw:
  cpus-per-task: 4
  mem: 32G
  cores: 4
  time: "02:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

multiqc_raw:
  cpus-per-task: 4
  mem: 32G
  cores: 4
  time: "02:00:00"
  name: "{rule}"
  output: logs/{rule}.out
  error: logs/{rule}.err

# ------------------------------------------------------------------------------
# Mageck
# ------------------------------------------------------------------------------

mageck_count:
  cpus-per-task: 16
  mem: 64G
  cores: 16
  time: "08:00:00"
  name: "{rule}.{wildcards.sample}"
  output: logs/{rule}.{wildcards.sample}.out
  error: logs/{rule}.{wildcards.sample}.err

