__default__:
    account: sansam-lab
    partition: serial
    time: 08:00:00
    cpus-per-task: 2
    mem: 16G
    output: results/logs/slurm-%x.%A.%a.log
    error: results/errors/slurm-%x.%A.%a.err

# ------------------------------------------------------------------------------
# Quality Control
# ------------------------------------------------------------------------------
fastqc_raw:
  cpus-per-task: 4
  mem: 8G
  time: "02:00:00"
  name: "{rule}.{wildcards.sample}"
  output: results/logs/{rule}.{wildcards.sample}.out
  error: results/logs/{rule}.{wildcards.sample}.err

multiqc_raw:
  cpus-per-task: 1
  mem: 16G
  time: "02:00:00"
  name: "{rule}"
  output: results/logs/{rule}.out
  error: results/logs/{rule}.err

# ------------------------------------------------------------------------------
# Make Temporary FASTQs
# ------------------------------------------------------------------------------
stage_fastqs:
  cpus-per-task: 2
  mem: 16G
  time: "02:00:00"
  name: "{rule}.{wildcards.sample}"
  output: results/logs/{rule}.{wildcards.sample}.out
  error: results/logs/{rule}.{wildcards.sample}.err

# ------------------------------------------------------------------------------
# Mageck Count
# ------------------------------------------------------------------------------
mageck_count:
  cpus-per-task: 16
  mem: 64G
  time: "08:00:00"
  name: "{rule}"
  output: results/logs/{rule}.out
  error: results/logs/{rule}.err

# ------------------------------------------------------------------------------
# Build Design Matrix
# ------------------------------------------------------------------------------
build_design_matrix:
  cpus-per-task: 1
  mem: 1G
  time: "00:30:00"
  name: "{rule}"
  output: results/logs/{rule}.out
  error: results/logs/{rule}.err

# ------------------------------------------------------------------------------
# Mageck MLE
# ------------------------------------------------------------------------------
mageck_mle:
  cpus-per-task: 16
  mem: 64G
  time: "08:00:00"
  name: "{rule}"
  output: results/logs/{rule}.out
  error: results/logs/{rule}.err

# ------------------------------------------------------------------------------
# Generate Plots
# ------------------------------------------------------------------------------
mageck_mle:
  cpus-per-task: 2
  mem: 64G
  time: "08:00:00"
  name: "{rule}"
  output: results/logs/{rule}.out
  error: results/logs/{rule}.err
