## samples file
samples_csv: "config/samples.csv"

## define mageck single end or paired end
mageck_paired: false
mageck_single: true

## sgRNA library
sgRNA_library: "resources/calabrese_library.txt"

# One counts file for all samples:
counts_prefix: "results/counts/sample1"

## environment modules
fastqc: "fastqc/0.12.1"
multiqc: "multiqc/1.21"
mageck: "mageck/0.5.9.2"
apptained: "apptainer/1.3.6"
