## samples file
samples_csv: "config/samples.csv"

## stage fastq files (mageck count cannot read from /archive drive)
stage_fastqs: false

## define mageck single end or paired end
mageck_paired: false

## path to sgRNA library
sgRNA_library: "resources/calabreseA_library.txt"         # for ko library use: "resources/brunelloKO_library.txt"

## One counts file for all samples:
counts_prefix: "sample1"

## MAGeCK MLE Settings
mle_enabled: true
mle_prefix: "CalabreseA"
mle_control_sgrna: ""      # optional; leave blank for none or use "resources/calabreseA_nonTargeting.txt" | "resources/brunelloKO_nonTargeting.txt"
custom_design_matrix: ""   # e.g. "resources/my_design.txt" to bypass auto-build

## MAGeCK Flute Settings
proj_name: "CalabreseA"
organism: "hsa"            # can also 
norm_method: "none"        # optional; can be "cc" or "loess"
fdr_threshold: 0.10

## Volcano Plot Settings
y_cap: 10                  # cap for -log10(FDR) in plots
effect_thr: 0.50           # draw vertical guides at ±effect_thr on Δβ

## environment modules
fastqc: "fastqc/0.12.1"
multiqc: "multiqc/1.21"
mageck: "mageck/0.5.9.2"
apptainer: "apptainer/1.3.6"
R: "R/4.4.1-mkl"
bioconductor: "bioconductor/3.19 gsl"
